### ISSUE TITLE
android vast ad taking too much time to show.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/google-media-framework-android#108]
when ever i show my videoplayer it takes too much time to show ad sometime it gives timeout. how to speed it up to show ad as soon as videoplayer initialize?

**Comment by ypavlotsky** [comment]
The ad can timeout if it takes too long to start playing the media after you call AdsManager.start(). That can happen for a variety of reasons, like network connectivity, etc. Can you give me the ad tag you're using to test?

**Comment by ZohaibGhafoor** [comment]
Can i load or prepare ad before user play it so user do not have to wait for ad prepairin or poading ?

**Comment by ypavlotsky** [comment]
Hi Zohaib,

I'm not seeing any timeouts with your tag. There is no ad preloading, so you'll have to load the ads when you want to play them.

**Comment by ZohaibGhafoor** [comment]
i have this ad Tag in our website as well as in android app. But on website it loads as we play and in app it takes time. and i can not understand my boss. He always show me the website example that why it is loading fast.
