### ISSUE TITLE
Can not play AD in dash or hls format .

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/google-media-framework-android#110]
I want to play ad in dash or hls format but it does not play it . but content is playing fine in dash format

**Comment by ypavlotsky** [comment]
Hi,

Could you send me the ad tag you're using to test? Thanks.

**Comment by ZohaibGhafoor** [comment]
here is the tag which give me error "Linear assests were found in the VAST ad response, but none of them matched the videoplayer capabilities.

https://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=/39243592/396388992&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]

**Comment by ypavlotsky** [comment]
To get GMF's ImaPlayer to play your ad, you're going to have to do two things.

1) Tell IMA that you support the HLS MIME type in AdsRenderingSettings.

      AdsRenderingSettings adsRenderingSettings =
          ImaSdkFactory.getInstance().createAdsRenderingSettings();
      ArrayList<String> arrayList = new ArrayList<String>(1);
      arrayList.add("application/x-mpegURL");
      adsRenderingSettings.setMimeTypes(arrayList);
      adsManager.init(adsRenderingSettings);

2) Set the VideoType when creating the SimpleVideoPlayer used to play ads.

     Video adVideo = new Video(adTagUrl.toString(), Video.VideoType.HLS);

Note that this code doesn't choose the video type intelligently, it just sets it to HLS. You might want to look at the extension and decision off of that.

**Comment by ZohaibGhafoor** [comment]
Sorry about that but can you please tell me in which file i have to put AdsRenderingSettings ?

**Comment by ypavlotsky** [comment]
In the demo, it's in ImaPlayer.java, in onAdsManagerLoaded().

**Comment by ZohaibGhafoor** [comment]
Yes Thanx it is working now but it is also giving me Toast error "The VAST ad tag response is empty."

**Comment by ypavlotsky** [comment]
Sorry, I can't help you with any ad serving issues. I would advise you to double-check your ad tag and correlator values.

**Comment by ZohaibGhafoor** [comment]
Ok thanx for your nice support. i will test it more and let you know if i have any problem from GMF side.
