### ISSUE TITLE
Cannot extend time of ad request from 15 seconds.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/google-media-framework-android#118]
Please help me how can i extend ad request timeout from 15 seconds to 30 seconds. because sometime my ad reached timeout on 15 seconds and i don'w want to miss any ad on any video from my client.

**Comment by ypavlotsky** [comment]
Hi Zohaib,

Currently, GMF doesn't support this because the underlying IMA SDK for Android doesn't expose this setting. I'll talk to the rest of the team and see if this is something we're able to do.

Thanks,
Yury Pavlotsky
IMA SDK Team
