### ISSUE TITLE
Make GMF available on Maven Central.

### ISSUE THREAD

**Issue by hariharsubramanyam** [googleads/google-media-framework-android#12]
It would be much easier for developers to integrate GMF into their projects if it is placed on Maven Central. Then, with just a few lines in build.gradle, they'll download it as a dependency.

Me or somebody else at Google should put this project on Maven Central. We also need to figure out what to do about Exoplayer, since it isn't on Maven Central. Do we put that on Maven Central too?

**Comment by noamtamim** [comment]
Reopened over a year ago. ExoPlayer is in jCenter now. It should be easy to also add GMF to jCenter.

**Comment by krzysiekbielicki** [comment]
I suppose that it can be closed...

**Comment by ypavlotsky** [comment]
GMF is now available on jCenter! 

You can include it in your build with:

compile 'com.google.android.libraries.mediaframework:mediaframework:0.2.1'

(Note: this version uses ExoPlayer 1.5.6)
