### ISSUE TITLE
Video jumps immediately before playback

### ISSUE THREAD

**Issue by dcostinett** [googleads/google-media-framework-android#127]
When I load content in the video player, I see the content jump or resize to full screen prior to playback starting. It's very fast, but hard to miss -- the content seems to get resized to fir the screen before getting sized properly. Even if I limit the height of the video_frame where I play back video to the fixed size of the video content, I still see the jump.

<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <FrameLayout
        android:id="@+id/video_frame"
        android:layout_width="match_parent"
        android:layout_height="match_parent" (setting fixed size here doesn't impact the problem)
        android:background="@color/colorDark"
        android:keepScreenOn="true"
        android:layout_centerInParent="true"
        tools:context="activity.VideoPlayerActivity" />

```
<include
    android:id="@+id/module_vide_progress_overlay"
    layout="@layout/progress_overlay"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_centerInParent="true" />
```

</RelativeLayout>

Anyone else noticed this? Is there a way to fix it?

**Comment by baptiste09** [comment]
Same behavior on my side.
It's not on every Android devices, but at least on:
- HTC Nexus 9
- Samsung Galaxy Tab S
- LG Nexus 4

 No known workaround at this time.

**Comment by ypavlotsky** [comment]
Sorry, which sample are you seeing this on?

**Comment by baptiste09** [comment]
No sample here.
We have integrated the player in our app, and for any media source, we can see the behavior described above.
With a previous player version (I need to check which one), we could see a flash instead of a jump/resize.
