### ISSUE TITLE
ExoPlayer 2.x.x

### ISSUE THREAD

**Issue by kamennik** [googleads/google-media-framework-android#129]
Hi,

ExoPlayer was updated to a new version, from 1.5.11 to 2.x.x, which is almost a completely different player. 
We have tested the Exoplayer 2.x.x and it seems to be a much better player. Unfortunately GMF is still at 1.5.7, which makes it unsuitable for our apps.

Do you guys plan on updating GMF to use Exoplayer 2.x.x anytime soon?

**Comment by SanPinto** [comment]
@kamennik ,
                    Did you try changing the Exo Player version in the GMF SDK. I increased the Exoplayer version to 2.0.2. But, I'm unable to import latest Explayer packages. It is not detecting any of the exoplayer 2.0.2 classes. Any idea why this is happening

**Comment by MudasirBhutto** [comment]
+1 for this. But it seems that these guys will not update this in near future.

**Comment by kamennik** [comment]
To whoever asked me about the exoplayer2 classes not detected: The Exoplayer2 is so much different, they have changed the namespace from: com.google.android.exoplayer to com.google.android.exoplayer2.

**Comment by ypavlotsky** [comment]
We're looking into Exoplayer v2, however we don't have a timeframe for migrating GMF to it right now.

**Comment by MudasirBhutto** [comment]
@ypavlotsky, thanks for updating us.

**Comment by noamtamim** [comment]
@ypavlotsky ExoPlayer2 has moved a lot of the code that was in the demo app (which is a basis for GMF) to the core. Which mean that in general, it should now be easier to integrate IMA and ExoPlayer(2).

**Comment by ypavlotsky** [comment]
I agree, it should be an easier integration. 

We're still formulating our strategy with regards to ExoPlayer v2, and I'll provide updates once I have them.

Thanks!

**Comment by Kiran89kumar** [comment]
Is thr any update?

**Comment by ypavlotsky** [comment]
No updates to report.

**Comment by hamadycisse** [comment]
+1, we would like to update to ExoPlayer 2.2.0 as well.

**Comment by hooked82** [comment]
Any updates on upgrading to the latest ExoPlayer?

**Comment by ypavlotsky** [comment]
No updates yet.

**Comment by asolis90** [comment]
Any updates on this?

**Comment by FrankSinghal** [comment]
Any updates?

**Comment by lzanol** [comment]
@ypavlotsky I'm also in need of this update, it'd provide us with playback speed switching and DVR for instance, which are important features for our business. Do you have any estimated time when you guys will be tackling it?

**Comment by eneim** [comment]
Just curious if PR is welcomed? If the issue is supporting resource I think people are willing to contribute.

**Comment by eneim** [comment]
FYI https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea

**Comment by ypavlotsky** [comment]
We recommend that users of GMF Android migrate to the [ExoPlayer IMA plugin](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima), which is supported by the ExoPlayer developers.

**Comment by MudasirBhutto** [comment]
We already did, cause they have added the IMA support almost in mid of 2017.
