### ISSUE TITLE
BehindLiveWindowException

### ISSUE THREAD

**Issue by SanPinto** [googleads/google-media-framework-android#130]
Hi, 
      I', using a GMF SDK to play Live TV. I'm using HLS stream. The Exo Player is throwing this error frequently:
[com.google.android.exoplayer.ExoPlaybackException: com.google.android.exoplayer.BehindLiveWindowException](url)

Can you please help me to diagnose the issue?

**Comment by brianchu** [comment]
You should able to figure something out from Exoplayer BehindLiveWindowException tickets:
https://github.com/google/ExoPlayer/issues?utf8=%E2%9C%93&q=is%3Aissue%20BehindLiveWindowException%20HLS
