### ISSUE TITLE
Black screen when play video

### ISSUE THREAD

**Issue by tannt275** [googleads/google-media-framework-android#131]
I have a problem, when video plays, screen is always black but voice always have. I don't know how to fix. Someone help me

**Comment by kamennik** [comment]
Check if you have a layer on top of the GMF player like a browser or some layout. Try bring to front.

**Comment by tannt275** [comment]
If have a layer on top of GMF player, why does the media controller still appear?

**Comment by brianchu** [comment]
I will check the media first. Play it in Exoplayer <2.X version demo app to see if the media can actually can play in your device. Searching on Exoplayer github issues also results in many complaints of black screen. Usually it is the device not support the media encoding types, some time it is the dimension of the media that the device not support.

**Comment by tannt275** [comment]
I think something happened with GMF(I clone GMF from github https://github.com/googleads/google-media-framework-android). I use same link video url in 2 screen. The first use FrameLayout and add ImaPlayer (I clone from Demo of GMF), video play with black screen. The second i use VideoView (in android default), this video plays normally. Some one help me?

**Comment by kamennik** [comment]
Did you set the background color of the framelayout to transparent?

**Comment by tannt275** [comment]
i don't know why have to set  background color of the framelayout to transparent? In your demo, background of it is black. OK i will set and test again

**Comment by tannt275** [comment]
@kamennik After I set background color of the framelayout to transparent, screen is still black. So i think the reason is not background color of the framelayout

**Comment by kamennik** [comment]
ok, as a last message, If you hear the sound, it means the player does play the stream. For some reason the picture is hidden. I would try to see if something is preventing the surface of the player to be displayed.
