### ISSUE TITLE
Enabling Proguard App is crashing

### ISSUE THREAD

**Issue by Kiran89kumar** [googleads/google-media-framework-android#132]
Proguard enabling making application to crash.

**Comment by ZohaibGhafoor** [comment]
i am using Proguard and it is working find. do not enable Proguard on GMF level. Enable it on your app level or app build.gradle. then it should work fine.

**Comment by ypavlotsky** [comment]
What ZohaibGhafoor said should work for you. You might also need to use '-dontwarn'. Check out the troubleshooting section of the ProGuard manual:

http://proguard.sourceforge.net/manual/troubleshooting.html
