### ISSUE TITLE
[BUG] Rotating Screen Causes ContentVideo to stop and Start All over with Ad

### ISSUE THREAD

**Issue by josefkorbel** [googleads/google-media-framework-android#133]
Everything is working as expected, only issue is that when Ad finishes and actual content video starts playing. When i rotate my device, the player dissapears (Because onDestroy is toggled) and the whole things starts again with Ad which is really annoying, any ideas how to fix this?

Thanks in advance,

Josef Korbel

**Comment by ypavlotsky** [comment]
I'm not seeing this issue when I run the demo. Can you describe the steps you're using to get this to happen?

Thanks.

**Comment by kamennik** [comment]
The question is quite old, nevertheless try to put this in the activity tag in your Androidmanifest.xml file:

android:configChanges="orientation|screenSize|keyboardHidden"

Lists configuration changes that the activity will handle itself. When a configuration change occurs at runtime, the activity is shut down and restarted by default, but declaring a configuration with this attribute will prevent the activity from being restarted. Instead, the activity remains running and its onConfigurationChanged() method is called.

https://developer.android.com/guide/topics/manifest/activity-element.html#config

**Comment by ypavlotsky** [comment]
The demo already has this implemented, so I'm going to close this issue. Please let me know if you encounter it again.
