### ISSUE TITLE
Distinguish between .mp3 and .mp4 contentMedia and change VideoType automatically

### ISSUE THREAD

**Issue by josefkorbel** [googleads/google-media-framework-android#134]
Greetings,

Im pullin my contents from API endpoint, however, some of them are .mp3 audiofiles, some of them are .mp4 video files, when i set VideoType to .mp4 , the videos work great, however, when .mp3 file comes to the player, nothing happend and its stuck after ad at 0:00, is it even possible to play .mp3 files in this player?

**Comment by ypavlotsky** [comment]
Hi there,

The player plays mp3 audio files just fine, you can try replacing one of the video URLs with a link to an audio mp3 and it will play successfully. What kind of errors are you seeing?

Thanks!

**Comment by shawnbuso** [comment]
Closing since this has been open for a few months with no response. If you still need help feel free to re-open.
