### ISSUE TITLE
Ads on Android TV

### ISSUE THREAD

**Issue by ricardomello** [googleads/google-media-framework-android#135]
Hi,

I'm trying to use GMF with an Android TV/Fire TV app, so far it's working without any issues with our Fire TV Stick, but on our Mi Box it does not work with any of the IMA sample tags. 

The error we are getting is DecoderInitializationException on MediaCodecTrackRenderer (DecoderInitFailed: OMX.amlogic.avc.decoder.awesome, MediaFormat(...)).

Is there anything we can do to make this work? I realize this may have something to with ExoPlayer, We tried increasing the version to 1.5.12, but that didn't work and v2 or higher has a lot of changes, it would break a lot of classes.

Thanks in advance.

**Comment by ypavlotsky** [comment]
Hi,

I don't have a Mi Box to test against, but your error points to a decoder error in the underlying ExoPlayer library. Some googling of the error seems to indicate it's hardware-specific, in that the device can't allocate the hardware decoder to render the track. Someone posted a similar issue on the ExoPlayer forums that might be relevant as far as software decoding workarounds: https://github.com/google/ExoPlayer/issues/273

The other thing I'd recommend is trying to load the ad video directly without going through the tag and see whether you can do that, or try to play the content video directly.

**Comment by ricardomello** [comment]
That was indeed the problem. It took me a while to fix it but switching to just one player for both content and ads fixed the issue.

Thanks for the help.
