### ISSUE TITLE
Issue in ad controls container don't appear

### ISSUE THREAD

**Issue by AhmedGamal-Inmobly** [googleads/google-media-framework-android#136]
Trying to make it work with exo player 2, get an issue with the ad container, sometimes it appears normally and sometimes it don't show.
and when it don't show and I try to inspect the layout I found that there's no webview inside the viewgroup I initialized the request with.

Any ideas why ?

**Comment by ypavlotsky** [comment]
Sorry, we haven't attempted to put ExoPlayer v2 into GMF yet, so I can't diagnose your issue.
