### ISSUE TITLE
*.srt Subtitle

### ISSUE THREAD

**Issue by ThiagoMiranda** [googleads/google-media-framework-android#137]
Hi.. After integrate the GMF player with my own application one of my clients asked for the possibility of using a subtitle. I've saw that you have a Subtitle Layer ( and an method onText ) that I could use but whats the best approach to do that?
Does GMF make all the fetching and parsing of the SRT file or should I do that on my own and just use the method to show the subtitles ( using the progress event, for instance )?
I couldn't find anything related to it on the repository. 

Thanks

**Comment by ypavlotsky** [comment]
Hi,

ExoPlayer's TextTrackRenderer should support SubRip files. Since GMF uses Exo v1, check out the Exo repo for more info: https://github.com/google/ExoPlayer/blob/release-v1/library/src/main/java/com/google/android/exoplayer/text/TextTrackRenderer.java

**Comment by ThiagoMiranda** [comment]
@ypavlotsky thanks!
