### ISSUE TITLE
How to insert two AdUri ?

### ISSUE THREAD

**Issue by josefkorbel** [googleads/google-media-framework-android#138]
Greetings,

Great work you have done here, im just curious about one thing, i have a service on backend, which gives me result with this structure 
- Status 
- DFPslot
- prerollUrl
- postrollUrl

Is there any way to pass different URLs for pre/postroll instead of VAST document ? or should i recreate VAST from my endpoint data ?

Thanks in advance.

**Comment by ypavlotsky** [comment]
Hi,

You can call requestAd() for multiple subsequent URLs, just be sure to destroy the ImaPlayer after you're done playing each ad. Alternatively, the framework supports using VMAP, where the timing and separate ad requests are handled automatically.

Thanks,
Yury

**Comment by shawnbuso** [comment]
Closing since this has been open >2 weeks without response, feel free to re-open if this is still an issue for you.
