### ISSUE TITLE
CompanionAd (Audio Ad with banner instead of Video)

### ISSUE THREAD

**Issue by josefkorbel** [googleads/google-media-framework-android#139]
Hello ! ,

I have just solved every problem i run into using this library and it is working really great, good job guys.

One thing that i still havent figured out yet. Sometimes my VAST xml returns with Audio Ad with Banner (CompanionAd most likely) instead of video. I have seen the guide on google developers, on how to implement Companion Ads in IMA sdk. But i havent found an elegant solution to this. Should i check if my add is returning in correct format, or what is the best way to show Image with audio only but ONLY when the VAST returns so in ContentContainer(ContentPlayer) ?

Greetings,
Josef Korbel

**Comment by ypavlotsky** [comment]
Are you trying to show the companion ad on top of the video player essentially like an interstitial? You can see what the content type of an ad is by using Ad.getContentType() and see whether the companion ad is filled by using CompanionAdSlot.isFilled().

**Comment by shawnbuso** [comment]
Closing since this has been open ~2 weeks with no response. If you still need help feel free to re-open.
