### ISSUE TITLE
When Ima Ad Uri is null sample app does not play the content stream.

### ISSUE THREAD

**Issue by pablichjenkov** [googleads/google-media-framework-android#140]
In sample app, the samples where no ads is displayed seems to not render any video to the screen. Some of the video has audio signal but not video. I tried on a Pixel with android 7.1.1 and a Galaxy Tablet with android 6.0.1. Same result in both.
The issue can be nailed down to when the imaUrl is null. I dont know what maybe cause this. Will check the code soon for more insights.

**Comment by shawnbuso** [comment]
Thanks for the info! I'll keep an eye out for your PR.
