### ISSUE TITLE
Exo player v2

### ISSUE THREAD

**Issue by saravananmaruthanayakam** [googleads/google-media-framework-android#142]
Can we manually add the Exo player version 2 to the google media framework library and use it.If so,is there any documentation available .

**Comment by shawnbuso** [comment]
Hi there,

Since this is an open source project you are free to download it and implement Exo v2 yourself. WE don't have any documentation on this, though, since we haven't implemented it ourselves yet.

Thanks,
Shawn Busolits
IMA SDK Team
