### ISSUE TITLE
Non linear ads

### ISSUE THREAD

**Issue by saravananmaruthanayakam** [googleads/google-media-framework-android#144]
Non linear ads are not getting played.

Here are my sample ad tags
"http://demo.tremorvideo.com/proddev/vast/vast1Nonlinear.xml"-    VAST 1.0

"http://demo.tremorvideo.com/proddev/vast/vast2Nonlinear.xml"-     VAST_2.0

**Comment by ypavlotsky** [comment]
Hi there,

The IMA Android SDK, which GMF-Android uses, doesn't support non-linear ads.
