### ISSUE TITLE
Question: Is there a way to change the video's rate?

### ISSUE THREAD

**Issue by ThiagoMiranda** [googleads/google-media-framework-android#145]
Hi...
Is there a way to fast forward a media? Like change its rate to 1.5 or 2x of the current speed?

Thanks

**Comment by ypavlotsky** [comment]
AFAIK, that's something that's supported out of the box in ExoPlayer v2 only. GMF is currently still using Exo v1.

**Comment by ThiagoMiranda** [comment]
@ypavlotsky so basically there isn't a way? Can I do something about it or just wait for the GMF support on Exov2?

**Comment by ypavlotsky** [comment]
If you want to implement it yourself, you can see various threads about it in the ExoPlayer GitHub repo. Exo v1 just doesn't have it already done for you.

**Comment by ThiagoMiranda** [comment]
@ypavlotsky I've been look into it since last week and I have to admit that I didn't find any topic about it. Can you lead me to one? I don't know if I'm querying the correct terms.

**Comment by ypavlotsky** [comment]
Here's the start of the discussion https://github.com/google/ExoPlayer/issues/26

**Comment by ThiagoMiranda** [comment]
@ypavlotsky Excelent. I've just bumped into it after your second reply. I'll look into it. Thanks a lot!
