### ISSUE TITLE
Video Player Inside Recyclerview

### ISSUE THREAD

**Issue by orhunkupeli** [googleads/google-media-framework-android#147]
I'm using player inside a recyclerview which has different types of items. However, I couldn't achieve to make it full screen. Is there any efficient method to make full screen my player inside recyclerview.

**Comment by eneim** [comment]
@orhunkupeli If you are about to use ExoPlayer 2.5+ (which also support ads), please take a look at [my library here](https://github/eneim/toro) :D.
