### ISSUE TITLE
Setting companion ad size in DIP

### ISSUE THREAD

**Issue by Crysis21** [googleads/google-media-framework-android#150]
Greetings everyone,

Recently I've been asked to integrate DFP for audio ads with companion creatives. The required companion ad should have a size of 300x250 (similar with AdMob). While the implementation is ok on iOS and the ad is displayed on a 300x250 points container, the android implementation renders the same ad in pixels and the result is like in the attached image.

Is there a way to scale the image to fit 300x250 DIP? 

![screenshot_20180118-151247](https://user-images.githubusercontent.com/777169/35099847-2e51c5cc-fc62-11e7-9745-1ce87dfe6000.png)

Thanks.

**Comment by ypavlotsky** [comment]
Hi. When you tell the SDK the size of your companion ad slot, it has to be in pixels. For example:

CompanionAdSlot companionAdSlot = mSdkFactory.createCompanionAdSlot();
companionAdSlot.setSize(728, 90);

**Comment by ypavlotsky** [comment]
Marking this as closed.
