### ISSUE TITLE
Support HLS

### ISSUE THREAD

**Issue by bshaparenko** [googleads/google-media-framework-android#21]
We depend on the [Exoplayer project](https://github.com/google/ExoPlayer). There is work under way to add support for HLS there, which will then get picked up by the Google Media Framework for Android project.

**Comment by tensafefrogs** [comment]
ExoPlayer fixed the rendering issues with big buck bunny and released the HLS updates, so I'm working on updating the ExoPlayer version in GMF now.

**Comment by tensafefrogs** [comment]
Fixed in #46
