### ISSUE TITLE
Break PlaybackControlLayer into multiple layers

### ISSUE THREAD

**Issue by hariharsubramanyam** [googleads/google-media-framework-android#25]
**Overview**: The PlaybackControlLayer class is quite complex and handles a LOT of functionality:
1. Play/pause buttons which are located in the center of the video player
2. Seekbar (and associated text views indicating the duration and elapsed time) displayed at the bottom of the video player for seeking to different parts of the video
3. Configurable logo in the top left of the video player
4. Title displayed in the top left of the video player (to the right of the logo)
5. Set of action buttons displayed in the top right of the video player (which behaves similarly to the Android action bar)
6. API for applying color scheme to the UI
7. Support for fullscreen playback
8. Mechanism for showing and fading out the playback UI

This functionality should be broken into multiple layers instead of being thrown into one layer.

**Device/OS**: All

**Related Issues**: None

**Suggest a Fix**: We should create on layer for the bottom bar (the seekbar and fullscreen button). We should create another layer for the top bar (the title, logo, and action buttons). The code to handle the action buttons and the code to handle fullscreen mode should each be moved to separate classes.

One potential challenge is getting all the playback UI to show and fade out together.

**Comment by ypavlotsky** [comment]
Closing as project will be deprecated Mar 15th, 2018.
