### ISSUE TITLE
Support for live streams

### ISSUE THREAD

**Issue by tensafefrogs** [googleads/google-media-framework-android#35]
We should add support for live streams. This feature may be dependent on HLS support since most live streaming events seem to be HLS these days, but if we can support a DASH live stream now we could get the player UI updated and ready so when HLS support is done we'll be all set to go.

This should include a UI update to support the different use cases:

Show some sort of "Live" indicator in the player control bar
A "go to live" button/option when watching the previous content in a live stream (say you are watching a live event but seek back a few minutes - sometimes you want to skip back to the "current" time in the stream)
Seekbar "loaded" indication should fill in from the right side, with the playhead starting at the far right. The "go to live" could simply be seeking all the way to the right.
Seeking into an unloaded segment (aka seeking all the way to the left) should not be allowed
Anything else we need to think about before getting started?

[TODO: Find a DASH live stream for testing, or we can wait for HLS support and use an HLS test stream]

**Comment by khurram25** [comment]
HLS Support is now available in new version. let close this issue by adding "Live" indicator

**Comment by ypavlotsky** [comment]
Closing this as project will be deprecated Mar 15th, 2018.
