### ISSUE TITLE
Ad playback does not finish

### ISSUE THREAD

**Issue by nfortenberry** [googleads/google-media-framework-android#40]
Occasionally ad playback gets stuck with a couple of seconds left and appears to buffer infinitely.  This causes the user to never actually be able to get to the real video content.  This has been replicated on many different devices on many different networks.  Unfortunately, I dont have a ton of additional details, but will update this issue as I continue to investigate.

**Comment by Larry322** [comment]
I see this issue when testing the preroll pods and midroll. When this happens,
the getCurrentPosition() and adPlayer.getDuration() always gives the same value.

@override
 public VideoProgressUpdate getAdProgress() {
        if (!mIsAdDisplayed || adPlayer.getDuration() <= 0) {
            return VideoProgressUpdate.VIDEO_TIME_NOT_READY;
        }
        return new VideoProgressUpdate(adPlayer.getCurrentPosition(),
                adPlayer.getDuration());
    }


L

**Comment by tensafefrogs** [comment]
Try the latest code from my last pull request: It updates ExoPlayer to the current release and may fix the issue.
