### ISSUE TITLE
CastCompanionLibrary-android Integration

### ISSUE THREAD

**Issue by khurram25** [googleads/google-media-framework-android#52]
Any idea how can we integrate casting option in ImaPlayer Class which contain separate references to SimpleVideoPlayer for content and Ads. assuming simplevideoplayer capable of casting,how can we cast pre-roll and mid-roll without affecting user experience

**Comment by tensafefrogs** [comment]
Hmm good question. The IMA SDK team is working on Chromecast support now, but the basic way is to cast your content, and if you also want to display the ad, you'd have to then cast the ad when the content pauses.

**Comment by ypavlotsky** [comment]
The IMA SDK team has added Cast functionality to the Advanced Example in the IMA Samples: https://github.com/googleads/googleads-ima-android/tree/master/AdvancedExample.

There is also a Cast receiver which uses IMA that works with the Android sender: https://github.com/googleads/googleads-ima-cast
