### ISSUE TITLE
Black screen flashing

### ISSUE THREAD

**Issue by brianchu** [googleads/google-media-framework-android#53]
Playing with the demo, I see every time when the ads or video starts (the very first time), the whole screen will flash with black color. Is there something with the ExoPlayer? or the famous VideoView black flash problem? Subsequent playback has no such problem. BTW, I test it on HTC M8.

**Comment by brianchu** [comment]
To be more precise, it happens when the ads video or video play the very first time, subsequent playback has no such problem. BTW, I test it on HTC M8.

**Comment by brianchu** [comment]
I replace Exoplayer jar file with the latest (in their master branch. Their dev has changed a lot and won't work with google media framework master) and I don't see any black flashing screen.

**Comment by tensafefrogs** [comment]
Ok great, I'll update the jar again soon (feel free to send a pull request if you make the needed changes!)

**Comment by brianchu** [comment]
sorry, I should apologize, I mistyped, what I mean is:

- Running Exoplay demo app (master and dev) and playing any video does not have any black flashing screen.
- Running GMF demo app with any version* of the Exoplay jar files, I still see the black flashing screen.

[*] except the dev branch, which can't compile with GMF right now.

**Comment by brianchu** [comment]
I wonder if anybody see the same problem as I do...

**Comment by Guro** [comment]
We have same issue here, does anyone got solution?

**Comment by ferrytanu** [comment]
ExoPlayer demo app hide the flash using [shutter view](https://github.com/google/ExoPlayer/blob/master/demo/src/main/res/layout/player_activity.xml#L38).
