### ISSUE TITLE
Easy customizable UI

### ISSUE THREAD

**Issue by brianchu** [googleads/google-media-framework-android#56]
1) Overview: It is not easy to customize the UI without touching the source codes directly, resulting not able to just use a jar file. Example: I want to force full screen with user rotate to landscape, non full screen for portrait. Adding a next video button. All these make me modify the PlaybackControlLayer class or work around it by adding callbacks here and there.

2) Device, OS: any device supported by this project.

3) Related issues: There is a suggestion for fullscreen sticky behaviour but it requires directly modifying the source codes.

4) Suggest a fix: Abstract out the (or delegate) a UI class (PlaybackControlLayer?) or provide a hook to let the app customize the UI completely.

**Comment by brianchu** [comment]
What do you think? Also, I can offer my help on this. One hacky thing I did is to create tons of callback and provide a customize but it is not ideal.

**Comment by tensafefrogs** [comment]
Yeah it's definitely on the road map.

I had planned on taking a similar approach that the iOS version of GMF takes: You can create and insert your own custom playback control layer (as you suggest) that adheres to a specific protocol.

I also wanted to move any of the control logic out of the UI classes so they simply emit a bunch of events or callbacks and have the activity (we should also convert the main class to an Activity Fragment) handle the callbacks and the playback control.
