### ISSUE TITLE
Race condition can cause ad player to be crated after Activity is closed.

### ISSUE THREAD

**Issue by evant** [googleads/google-media-framework-android#58]
Even after `release()` is called, the `VideoAdPlayer` callbacks can fire, triggering the creation on the ad player and causing it to play in the background. I worked around this by adding an `isReleased` flag in the `ImaPlayer` player and checking it in the callbacks of the `VideoAdPlayer`. I don't know if this is a proper solution or if `adsLoader.contentComplete()` should be more immediate in preventing the callbacks from firing.

**Comment by khurram25** [comment]
#55 is also occured due to this same reason. VideoAdPlayer callbacks are fired even after release.  we have also fixed with this by using similar kind of flag. 

@tensafefrogs  please comment/patch this small issue.
