### ISSUE TITLE
Exoplayer version sync with GMF

### ISSUE THREAD

**Issue by brianchu** [googleads/google-media-framework-android#59]
Overview: What is the official Exoplayer version that work with GMF master branch?
I tried to drop the latest Exoplayer but it seems there are some interface change there.
I really want the latest Exoplayer since it fixed some of the bugs that really important.
Thanks

Devices: All GMF supported
Related issues: -
Suggest a fix: a merge ?

**Comment by tensafefrogs** [comment]
The current jar is v1.2.1, which is a few months old. I just manually update it occasionally and manually update the integration as needed. Feel free to send a pull request if you want to update to the latest jar.

It looks like v1.2.4 is the latest release: https://github.com/google/ExoPlayer/releases
