### ISSUE TITLE
DASH Streams Died

### ISSUE THREAD

**Issue by steg132** [googleads/google-media-framework-android#64]
It appears that the dash streams that are being used in the demo are not working anymore. It looks like Youtube is returning "403 Forbidden" responses to video urls in the app. Am I missing 

I have tested on multiple devices, across networks. Hopefully, this isn't just me?

Thanks!

**Comment by tensafefrogs** [comment]
Hmm, it's possible. I'll see if we can get some replacement streams.

**Comment by ypavlotsky** [comment]
Closing this out due to age.
