### ISSUE TITLE
Update to latest ExoPlayer

### ISSUE THREAD

**Issue by noamtamim** [googleads/google-media-framework-android#66]
There are changes in ExoPlayer that were done as early as April of this year (https://github.com/google/ExoPlayer/commit/4c8f9a8, https://github.com/google/ExoPlayer/commit/9921dfd), which broke compatibility with this library. Are there any plans to fix?
The README entry "I want to use a newer version of Exoplayer" doesn't really help.

My app needs the updates in ExoPlayer, but it also needs this library.

**Comment by anggras** [comment]
Created a fork at https://github.com/Gratif/google-media-framework-android to be compatible with ExoPlayer 1.5.1
Please let me know if it's good, thx

**Comment by noamtamim** [comment]
Great, thanks for this work. 
Is it ready for testing or still work in progress?

**Comment by anggras** [comment]
It should be ready for testing
