### ISSUE TITLE
"Unable to handle cue points, no content progress provider configured"

### ISSUE THREAD

**Issue by sfacs** [googleads/google-media-framework-android#77]
In the demo app, when trying to read the following video list:
new VideoListItem("AdRules - Apple test (HLS)",
            new Video("https://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/" +
                "bipbop_4x3_variant.m3u8 ",
                Video.VideoType.HLS),
                "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator="),
    };

**Comment by Bhavdip** [comment]
Hello I have the similar issue when tried to load the three-roll ads. It throw exception inside AdListener it shows the message such like "Unable to handle cue points, no content progress provider configured".

Have any idea what is the correct way to add the ads link url ?

Thanks

**Comment by madhurkapadia** [comment]
add below code in ImaPlayer
private ContentProgressProvider mContentProgressProvider;

 mContentProgressProvider = new ContentProgressProvider() {
            @Override
            public VideoProgressUpdate getContentProgress() {
                if (mIsAdDisplayed || contentPlayer.getDuration() <= 0) {
                    return VideoProgressUpdate.VIDEO_TIME_NOT_READY;
                }
                return new VideoProgressUpdate(contentPlayer.getCurrentPosition(),
                        contentPlayer.getDuration());
            }
        }; 

add in AdsRequest
request.setContentProgressProvider(mContentProgressProvider);
