### ISSUE TITLE
Race Condition can cause fullscreen toggle button to be visible in ImaPlayer even if we call setFullscreenCallback with null. NullPointerException occurs if toggle button is pressed

### ISSUE THREAD

**Issue by kazo0** [googleads/google-media-framework-android#78]
<b>Device/OS</b>
OnePlus One / 6.0.1
Samsung Galaxy Tab S / 4.4.2
VS Emulator / 5.0

Will occur on any device/OS

<b>Overview</b>
Issue stems from the setFullscreenCallback method in ImaPlayer.java. If you are using the adPlayer along with the contentPlayer, then there may be issues when trying to set the fullscreenCallback to null on the ImaPlayer. the setFullscreenCallback method sets ImaPlayer's private fullscreenCallback variable to a new PlaybackControlLayer.FullscreenCallback() even if you pass in null to the method. This can cause concurrency issues when the ImaPlayer is attempting to destroy the adPlayer after the ad has finished and launch the contentPlayer. When destroying the adPlayer, ImaPlayer calls its own setFullscreenCallback with its private variable fullscreenCallback which, sometimes, may result in a non-null callback being propograted to the contentPlayer SimpleVideoPlayer. Causing the toggle button to be visible

<b>Fix</b>

ImaPlayer's setFullscreenCallback method should only set this.fullscreenCallback if the method parameter is non-null, otherwise it should be null as well.

Will make a pull request when I get home

**Comment by ypavlotsky** [comment]
Hi Steve,

How do you get the race condition to happen?

**Comment by kazo0** [comment]
Oh sorry, I forgot to put my steps, it seems to happen when I have poor connection quality. So while it takes a while to load the ad and the content video. I can also get it to happen artificially by debugging and placing breakpoints in the ImaPlayer's setFullscreenCallback method so I can pause the flow.
