### ISSUE TITLE
Ad Playback does not continue after clicking 'Learn more'-Button

### ISSUE THREAD

**Issue by thomaspaulmann** [googleads/google-media-framework-android#80]
The ad playback is paused when clicking the 'Learn more'-Button, but the playback is not automatically continued when coming back to the app and the controls are hidden. The user can not react to anything and have to restart this or a new video.

**Comment by Kiran89kumar** [comment]
Any update on this issue?

**Comment by ZohaibGhafoor** [comment]
I did it myself. for now you have to put some of your own logics. GMF is just a ad request response platform. You have to implement your own logic of your needs.
