### ISSUE TITLE
Weird ad link

### ISSUE THREAD

**Issue by b95505017** [googleads/google-media-framework-android#96]
[http://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=%2F6062%2Fgmf_demo&ciu_szs&impl=s&gdfp_req=1&env=vp&output=xml_vast3&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]&ad_rule=1&cmsid=11924&vid=cWCkSYdFlU0&cust_params=gmf_format%3Dstd%2Cskip](http://pubads.g.doubleclick.net/gampad/ads?sz=400x300&iu=%2F6062%2Fgmf_demo&ciu_szs&impl=s&gdfp_req=1&env=vp&output=xml_vast3&unviewed_position_start=1&url=[referrer_url]&correlator=[timestamp]&ad_rule=1&cmsid=11924&vid=cWCkSYdFlU0&cust_params=gmf_format%3Dstd%2Cskip)

[in the sample](https://github.com/googleads/google-media-framework-android/blob/master/demo/src/main/java/com/google/googlemediaframeworkdemo/demo/MainActivity.java#L252)

**Comment by ypavlotsky** [comment]
Replaced with a working ad tag.
